export const women=[
    {
        id:1,
      image: '/src/assets/Women-assets/women-product-1.jpg',
      title: 'Fabrics 3 Piece Suit',
      description: 'Printed Lawn | Top Bottoms Dupatta',
      price:'13.54$',
    },
    {
        id:2,
      image: '/src/assets/Women-assets/women-product-2.jpg',
      title: 'Fabrics 3 Piece Suit',
      description: 'Printed Lawn | Top Bottoms Dupatta',
      price:'13.54$',
    },
    {
        id:3,
        image: '/src/assets/Women-assets/women-product-3.jpg',
        title: 'Indigo Charm Kurta',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
      },
      {
        id:4,
        image: '/src/assets/Women-assets/women-product-4.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
      },
      {
        id:5,
        image: '/src/assets/Women-assets/women-product-5.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
      },
      {
        id:6,
        image: '/src/assets/Women-assets/women-product-6.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
      },
      {
        id:7,
        image: '/src/assets/Women-assets/women-product-7.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
      },
      {
        id:8,
        image: '/src/assets/Women-assets/women-product-8.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
      },
      {
        id:9,
        image: '/src/assets/Women-assets/women-product-9.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
      },
      {
        id:10,
        image: '/src/assets/Women-assets/women-product-10.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
      },
      {
        id:11,
        image: '/src/assets/Women-assets/women-product-11.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
      },
      {
        id:12,
        image: '/src/assets/Women-assets/women-product-12.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
      },
      {
        id:13,
        image: '/src/assets/Women-assets/women-product-13.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
      },
      {
        id:14,
        image: '/src/assets/Women-assets/women-product-14.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
      },
      {
        id:15,
        image: '/src/assets/Women-assets/women-product-15.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
      },
      {
        id:16,
        image: '/src/assets/Women-assets/women-product-16.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
      },

  ]