export const men=[
    {
        id:1,
      image: '/src/assets/Men-assets/men-product-1.jpg',
      title: 'Basic mustard kurta',
      description: 'Basic mustard |shalwar Lahori pajama',
      price:'10.16$',
    },
    {
        id:2,
      image: '/src/assets/Men-assets/men-product-2.jpg',
      title: 'Basic mustard kurta',
      description: 'Basic mustard |shalwar Lahori pajama',
      price:'10.16$',
    },
    {
        id:3,
        image: '/src/assets/Men-assets/men-product-3.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
      },
      {
        id:4,
        image: '/src/assets/Men-assets/men-product-4.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
      },
      {
        id:5,
        image: '/src/assets/Men-assets/men-product-5.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
      },
      {
        id:6,
        image: '/src/assets/Men-assets/men-product-6.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
      },
      {
        id:7,
        image: '/src/assets/Men-assets/men-product-7.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
      },
      {
        id:8,
        image: '/src/assets/Men-assets/men-product-8.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
      },
      {
        id:9,
        image: '/src/assets/Men-assets/men-product-9.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
      },
      {
        id:10,
        image: '/src/assets/Men-assets/men-product-10.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
      },
      {
        id:11,
        image: '/src/assets/Men-assets/men-product-15.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
      },
      {
        id:12,
        image: '/src/assets/Men-assets/men-product-16.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
      },
      {
        id:13,
        image: '/src/assets/Men-assets/men-product-11.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
      },
      {
        id:14,
        image: '/src/assets/Men-assets/men-product-12.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
      },
      {
        id:15,
        image: '/src/assets/Men-assets/men-product-13.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
      },
      {
        id:16,
        image: '/src/assets/Men-assets/men-product-14.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
      },

  ]