export const salemen=[
    {
      id:1,
      image: '/src/assets/Sale-assets/sale-product-9.jpg',
      title: 'Basic mustard kurta',
      description: 'Basic mustard |shalwar Lahori pajama',
      price:'10.16$',
      discount:'30%',
    },
    {
      id:2,
      image: '/src/assets/Sale-assets/sale-product-10.jpg',
      title: 'Basic mustard kurta',
      description: 'Basic mustard |shalwar Lahori pajama',
      price:'10.16$',
      discount:'25%',
    },
    {
      id:3,
        image: '/src/assets/Sale-assets/sale-product-11.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
        discount:'10%',
      },
      {
        id:4,
        image: '/src/assets/Sale-assets/sale-product-12.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
        discount:'45%',
      },
      {
        id:5,
        image: '/src/assets/Sale-assets/sale-product-13.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
        discount:'15%',
      },
      {
        id:6,
        image: '/src/assets/Sale-assets/sale-product-14.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
        discount:'30%',
      },
      {
        id:7,
        image: '/src/assets/Sale-assets/sale-product-15.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
        discount:'10%',
      },
      {
        id:8,
        image: '/src/assets/Sale-assets/sale-product-16.jpg',
        title: 'Basic mustard kurta',
        description: 'Basic mustard |shalwar Lahori pajama',
        price:'10.16$',
        discount:'15%',
      },
  ]
//   const [womenData, setWomenData] = useState([
//     {
//       image: '/src/assets/Sale-assets/sale-product-1.jpg',
//       title: 'Fabrics 3 Piece Suit',
//       description: 'Printed Lawn | Top Bottoms Dupatta',
//       price:'13.54$',
//       discount:'10%',
//     },
//     {
//       image: '/src/assets/Sale-assets/sale-product-2.jpg',
//       title: 'Fabrics 3 Piece Suit',
//       description: 'Printed Lawn | Top Bottoms Dupatta',
//       price:'13.54$',
//       discount:'10%',
//     },
//     {
//         image: '/src/assets/Sale-assets/sale-product-3.jpg',
//         title: 'Fabrics 3 Piece Suit',
//         description: 'Printed Lawn | Top Bottoms Dupatta',
//         price:'13.54$',
//         discount:'10%',
//       },
//       {
//         image: '/src/assets/Sale-assets/sale-product-4.jpg',
//         title: 'Fabrics 3 Piece Suit',
//         description: 'Printed Lawn | Top Bottoms Dupatta',
//         price:'13.54$',
//         discount:'10%',
//       },
//       {
//         image: '/src/assets/Sale-assets/sale-product-5.jpg',
//         title: 'Fabrics 3 Piece Suit',
//         description: 'Printed Lawn | Top Bottoms Dupatta',
//         price:'13.54$',
//         discount:'10%',
//       },
//       {
//         image: '/src/assets/Sale-assets/sale-product-6.jpg',
//         title: 'Fabrics 3 Piece Suit',
//         description: 'Printed Lawn | Top Bottoms Dupatta',
//         price:'13.54$',
//         discount:'10%',
//       },
//       {
//         image: '/src/assets/Sale-assets/sale-product-7.jpg',
//         title: 'Fabrics 3 Piece Suit',
//         description: 'Printed Lawn | Top Bottoms Dupatta',
//         price:'13.54$',
//         discount:'10%',
//       },
//       {
//         image: '/src/assets/Sale-assets/sale-product-8.jpg',
//         title: 'Fabrics 3 Piece Suit',
//         description: 'Printed Lawn | Top Bottoms Dupatta',
//         price:'13.54$',
//         discount:'10%',
//       },
//   ]