export const salewomen=[
    {
        id:1,
      image: '/src/assets/Sale-assets/sale-product-1.jpg',
      title: 'Fabrics 3 Piece Suit',
      description: 'Printed Lawn | Top Bottoms Dupatta',
      price:'13.54$',
      discount:'10%',
    },
    {
        id:2,
      image: '/src/assets/Sale-assets/sale-product-2.jpg',
      title: 'Fabrics 3 Piece Suit',
      description: 'Printed Lawn | Top Bottoms Dupatta',
      price:'13.54$',
      discount:'10%',
    },
    {
        id:3,
        image: '/src/assets/Sale-assets/sale-product-3.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
        discount:'10%',
      },
      {
        id:4,
        image: '/src/assets/Sale-assets/sale-product-4.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
        discount:'10%',
      },
      {
        id:5,
        image: '/src/assets/Sale-assets/sale-product-5.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
        discount:'10%',
      },
      {
        id:6,
        image: '/src/assets/Sale-assets/sale-product-6.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
        discount:'10%',
      },
      {
        id:7,
        image: '/src/assets/Sale-assets/sale-product-7.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
        discount:'10%',
      },
      {
        id:8,
        image: '/src/assets/Sale-assets/sale-product-8.jpg',
        title: 'Fabrics 3 Piece Suit',
        description: 'Printed Lawn | Top Bottoms Dupatta',
        price:'13.54$',
        discount:'10%',
      },
  ]